"""initial schema

Revision ID: 304238491ab3
Revises: 
Create Date: 2026-06-30 00:18:38.087896
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '304238491ab3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Required extensions (docs/03 §5): gen_random_uuid() and trigram fuzzy match.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_he', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('code', name=op.f('uq_achievements_code'))
    )
    op.create_table('foods',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_he', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('is_liquid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('kcal_per_100', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_per_100', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_per_100', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_per_100', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fiber_per_100', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sugar_per_100', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sodium_mg_per_100', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('is_processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('saturated_fat_per_100', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods'))
    )
    op.create_index('idx_foods_barcode', 'foods', ['barcode'], unique=False)
    op.create_index('idx_foods_name_trgm', 'foods', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_he', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cadence', sa.Text(), server_default=sa.text("'daily'"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('code', name=op.f('uq_tasks_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('firebase_uid', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'other', name='sex_enum'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activity_level_enum'), nullable=True),
    sa.Column('locale', sa.Text(), server_default=sa.text("'he'"), nullable=False),
    sa.Column('units_metric', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('streak_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('onboarded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('firebase_uid', name=op.f('uq_users_firebase_uid'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chat_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('idx_chat_user_time', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kcal_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('kcal_target', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('water_ml', sa.Integer(), nullable=True),
    sa.Column('meals_count', sa.SmallInteger(), nullable=True),
    sa.Column('health_score', sa.SmallInteger(), nullable=True),
    sa.Column('goal_met', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_summaries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_summaries')),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_summaries_user_date')
    )
    op.create_index('idx_daily_user_date', 'daily_summaries', ['user_id', sa.literal_column('date DESC')], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('fcm_token', name=op.f('uq_devices_fcm_token'))
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.Enum('lose_weight', 'gain_muscle', 'maintain', name='goal_type_enum'), nullable=False),
    sa.Column('start_weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('bmr_kcal', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('tdee_kcal', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('daily_kcal_target', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('protein_g_target', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('carbs_g_target', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('fat_g_target', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('water_ml_target', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_index('uq_goals_one_active_per_user', 'goals', ['user_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('meals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'), nullable=False),
    sa.Column('eaten_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('photo', 'manual', 'barcode', 'recipe', name='meal_source_enum'), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('total_kcal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_protein_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_carbs_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_fat_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_fiber_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_sugar_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_sodium_mg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('health_score', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_index('idx_meals_user_date', 'meals', ['user_id', sa.literal_column('logged_date DESC')], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('meal_reminder', 'water_reminder', 'coach', 'achievement', 'custom', name='notif_type_enum'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notif_user_sched', 'notifications', ['user_id', 'scheduled_for'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_he', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('prep_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('servings', sa.SmallInteger(), nullable=True),
    sa.Column('kcal_per_serving', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_g_per_serving', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_g_per_serving', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_g_per_serving', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements')),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievements_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_table('user_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_user_tasks_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tasks')),
    sa.UniqueConstraint('user_id', 'task_id', 'date', name='uq_user_tasks_user_task_date')
    )
    op.create_index(op.f('ix_user_tasks_task_id'), 'user_tasks', ['task_id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_water_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_logs'))
    )
    op.create_index('idx_water_user_date', 'water_logs', ['user_id', 'logged_date'], unique=False)
    op.create_table('weight_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('bmi', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('measured_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('manual', 'google_fit', 'samsung_health', 'healthkit', name='weight_source_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weight_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_history'))
    )
    op.create_index('idx_weight_user_time', 'weight_history', ['user_id', sa.literal_column('measured_at DESC')], unique=False)
    op.create_table('coach_insights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('meal', 'daily', 'weekly', name='insight_scope_enum'), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_coach_insights_meal_id_meals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coach_insights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_insights'))
    )
    op.create_index('idx_insights_user_time', 'coach_insights', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_coach_insights_meal_id'), 'coach_insights', ['meal_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('source', sa.Enum('ai', 'catalog', 'manual', name='item_source_enum'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('kcal', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('edited_by_user', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_meal_items_food_id_foods')),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_items_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_items'))
    )
    op.create_index('idx_meal_items_meal', 'meal_items', ['meal_id'], unique=False)
    op.create_index(op.f('ix_meal_items_food_id'), 'meal_items', ['food_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('display_amount', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_recipe_ingredients_food_id_foods')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients'))
    )
    op.create_index(op.f('ix_recipe_ingredients_food_id'), 'recipe_ingredients', ['food_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('checked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_shopping_list_items_recipe_id_recipes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_list_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_list_items'))
    )
    op.create_index(op.f('ix_shopping_list_items_recipe_id'), 'shopping_list_items', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_user_id'), 'shopping_list_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_items_user_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_recipe_id'), table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_food_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_meal_items_food_id'), table_name='meal_items')
    op.drop_index('idx_meal_items_meal', table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_coach_insights_meal_id'), table_name='coach_insights')
    op.drop_index('idx_insights_user_time', table_name='coach_insights')
    op.drop_table('coach_insights')
    op.drop_index('idx_weight_user_time', table_name='weight_history')
    op.drop_table('weight_history')
    op.drop_index('idx_water_user_date', table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_user_tasks_task_id'), table_name='user_tasks')
    op.drop_table('user_tasks')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index('idx_notif_user_sched', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_meals_user_date', table_name='meals')
    op.drop_table('meals')
    op.drop_index('uq_goals_one_active_per_user', table_name='goals', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('idx_daily_user_date', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index('idx_chat_user_time', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_index('idx_foods_name_trgm', table_name='foods', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_foods_barcode', table_name='foods')
    op.drop_table('foods')
    op.drop_table('achievements')
    # Drop the ENUM types created inline with the tables above.
    for enum_name in (
        'sex_enum',
        'activity_level_enum',
        'goal_type_enum',
        'meal_type_enum',
        'meal_source_enum',
        'item_source_enum',
        'insight_scope_enum',
        'chat_role_enum',
        'notif_type_enum',
        'weight_source_enum',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
